version: '3'

services:
  web:
    container_name: pok_python
#    image: konstantinrjab/python_poker
    build:
      context: web
    environment:
      APP_SETTINGS: 'config.DevelopmentConfig'
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"
  mysql:
    container_name: poker_mysql
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'poker'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - poker_mysql:/var/lib/mysql
volumes:
  poker_mysql: